# fly.toml app configuration file generated for absolute-ear on 2026-02-28T16:07:55-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'absolute-ear'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
